### ISSUE TITLE
Cannot build for iOS

### ISSUE THREAD

**Issue by igiazlas** [MythiCode/zebra_utlity#1]
Building for iOS fails with
`ld: library not found for -lZSDK_API`

Version: 0.0.31

**Comment by hrshs** [comment]
There is `libZSDK_API.a` file in the ios folder for this repose. Please open your Xcode project add manually this library to your Xcode.

**Comment by igiazlas** [comment]
Thank you. It worked

**Comment by bshaik1** [comment]
> There is `libZSDK_API.a` file in the ios folder for this repose. Please open your Xcode project add manually this library to your Xcode.

I added libZSDK_API.a file through 'Link Binary With Libraries' and it still doesn't work. I am using 0.0.32

**Comment by bttruman** [comment]
We were able to get this working by simply right clicking on "Runner" at the top of the solution explorer, and selecting "Add File to *Project Name*". This added the file to the correct location in the project for it to be referenced properly.

**Comment by Kirubhasankar** [comment]
Found the issue in plugin. Need to add '.a' extension as like ( s.vendored_libraries = 'libZSDK_API.a' ) in zebrautility.podspec

**Comment by crushman1** [comment]
> There is `libZSDK_API.a` file in the ios folder for this repose. Please open your Xcode project add manually this library to your Xcode.

How exactly does one go about doing this ?
