### ISSUE TITLE
Cannot build on iOS

### ISSUE THREAD

**Issue by richardzamora** [MythiCode/zebra_utlity#3]
I tried to run in a new project importing this library in the pubspec.yaml (  zebrautility: ^0.0.38 ) and the project didn't compile. I'm new with Xcode.
This is the error:
Undefined symbols for architecture x86_64:
      "_OBJC_CLASS_$_EAAccessory", referenced from:
          objc-class-ref in zebrautility(Printer.o)
      "_OBJC_CLASS_$_EASession", referenced from:
          objc-class-ref in libZSDK_API.a(Zebra_EADSessionController.o)
      "_OBJC_CLASS_$_EAAccessoryManager", referenced from:
          objc-class-ref in libZSDK_API.a(MfiBtPrinterConnection.o)
          objc-class-ref in zebrautility(Printer.o)
    ld: symbol(s) not found for architecture x86_64

**Comment by yeminsoe** [comment]
i think  zebrautility has many issues

**Comment by hrshs** [comment]
You can refer to this closed [issue.](https://github.com/MythiCode/zebra_utlity/issues/1)
