### ISSUE TITLE
Error when the instance is created like on documentation

### ISSUE THREAD

**Issue by alcampospalacios** [MythiCode/zebra_utlity#7]
The syntax error says Too many positional arguments : 0 expected, but 3 founds. Try removing the extra positional arguments, or specifyieng the name for named arguments.
![image](https://user-images.githubusercontent.com/54634181/133952897-46b96208-4c1a-4d07-a83e-809cd81afa96.png)

Now, when I do what the error message suggests I have another error like in the image below

![image](https://user-images.githubusercontent.com/54634181/133953499-b3471a1f-ecd4-4c42-bac7-34f3c18543f6.png)

**Comment by alcampospalacios** [comment]
Apparently the problem was that the parameters of the method. This is the way:

ZebraPrinter zebraPrinter = await Zebrautility.getPrinterInstance(
      onPrinterFound: onPrinterFound('hoid-connect', '192.168.43.80', true),
      onPrinterDiscoveryDone: onPrinterDiscoveryDone,
      onChangePrinterStatus: onChangePrinterStatus,
      onPermissionDenied: onPermissionDenied);

  print(zebraPrinter);

  zebraPrinter.connectToPrinter("192.168.43.80");
  zebraPrinter.print(data);
}

Function onPrinterFound = (String name, String ipAddress, bool isWifi) {
  print("PrinterFound :" + name + ipAddress);
};

**Comment by patelnirav48** [comment]
@alcampospalacios By seeing this it seems here we need to pass fixed ip address instead from discovered list? what if we need to display list of printers and by clicking on that it will connectToPrinter? How can we achieve that?

**Comment by gmauro99** [comment]
Hello,

i've the same problem, I would to connect to device after discovered list is called, how can I do that?
